-- Baseline schema: the tables V1..V8 assume already exist.
--
-- Before Flyway was introduced these tables were created by Hibernate's ddl-auto=update, and
-- V1 onward only alters them. On a fresh database Flyway runs before Hibernate, so V1 failed
-- with 'relation "users" does not exist'. This migration creates them first.
--
-- Shapes are taken from a Hibernate-generated schema of the current entity mappings (the
-- columns later migrations add, e.g. roles.active, users.phone, product_sizes.status, are
-- included; those migrations use IF NOT EXISTS so they're no-ops here).
--
-- Existing databases were baselined at version 0 (spring.flyway.baseline-version), so Flyway
-- treats this migration as below baseline and never runs it against them.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    phone           VARCHAR(30),
    profile_image   VARCHAR(255),
    active          BOOLEAN NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX idx_user_email ON users (email);

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    active          BOOLEAN NOT NULL,
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE user_roles (
    user_id         BIGINT NOT NULL REFERENCES users (id),
    roles_id        BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (roles_id, user_id)
);

CREATE TABLE user_credentials (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL REFERENCES users (id),
    alias               VARCHAR(255),
    password_change_at  TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT user_credentials_user_id_key UNIQUE (user_id)
);

CREATE TABLE password_reset_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    token           VARCHAR(255) NOT NULL,
    issued_at       TIMESTAMP(6) NOT NULL,
    expiry_date     TIMESTAMP(6) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT password_reset_tokens_token_key UNIQUE (token)
);

CREATE TABLE addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    street          VARCHAR(150) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    state           VARCHAR(100) NOT NULL,
    zip_code        VARCHAR(20) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    is_default      BOOLEAN NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL
);

CREATE TABLE brands (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    image           VARCHAR(500),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT brands_slug_key UNIQUE (slug)
);

CREATE TABLE categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    image           VARCHAR(500),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT categories_slug_key UNIQUE (slug)
);

CREATE TABLE sub_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL REFERENCES categories (id),
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT sub_categories_slug_key UNIQUE (slug),
    CONSTRAINT uk_sub_category_category_name UNIQUE (category_id, name)
);

CREATE INDEX idx_sub_category_category ON sub_categories (category_id);

CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255) NOT NULL,
    slug              VARCHAR(255) NOT NULL,
    description       TEXT,
    image_cover       VARCHAR(500),
    stock_quantity    INTEGER,
    ratings_average   NUMERIC(3, 2) NOT NULL,
    ratings_quantity  INTEGER NOT NULL,
    brand_id          BIGINT REFERENCES brands (id),
    sub_category_id   BIGINT NOT NULL REFERENCES sub_categories (id),
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT products_slug_key UNIQUE (slug)
);

CREATE INDEX idx_product_brand ON products (brand_id);
CREATE INDEX idx_product_sub_category ON products (sub_category_id);

CREATE TABLE product_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT NOT NULL REFERENCES products (id),
    image_url       VARCHAR(500) NOT NULL,
    sort_order      INTEGER NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_product_image_product ON product_images (product_id);

CREATE TABLE product_sizes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    description     VARCHAR(255),
    status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT product_sizes_name_key UNIQUE (name)
);

-- "prouduct_id" and "create_at" (DATE) mirror the current ProductVariants mapping as-is.
CREATE TABLE product_variants (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prouduct_id           BIGINT REFERENCES products (id),
    product_size_id       BIGINT REFERENCES product_sizes (id),
    sku                   VARCHAR(50) NOT NULL,
    color                 VARCHAR(50),
    price                 NUMERIC(19, 2) NOT NULL,
    price_after_discount  NUMERIC(38, 2),
    sold_quantity         INTEGER,
    create_at             DATE NOT NULL,
    update_at             TIMESTAMP(6),
    CONSTRAINT product_variants_sku_key UNIQUE (sku)
);

CREATE TABLE inventories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id  BIGINT NOT NULL REFERENCES product_variants (id),
    quantity            INTEGER NOT NULL CHECK (quantity >= 0),
    reserved_quantity   INTEGER NOT NULL CHECK (reserved_quantity >= 0),
    version             BIGINT,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT inventories_product_variant_id_key UNIQUE (product_variant_id)
);

CREATE TABLE inventory_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id     BIGINT NOT NULL REFERENCES inventories (id),
    type             VARCHAR(30) NOT NULL CHECK (type IN ('PURCHASE', 'SALE', 'RETURN', 'ADJUSTMENT', 'DAMAGE', 'LOSS')),
    quantity_change  INTEGER NOT NULL,
    reference_type   VARCHAR(30),
    reference_id     BIGINT,
    note             VARCHAR(255),
    created_at       TIMESTAMP(6) NOT NULL
);
